# **Exercise: Basics of Python and Numpy**

1. Import numpy and print the numpy version. (Hint: use ```__version___``` attribute to check package version.)

In [3]:
import numpy as np
print("NumPy:", np.__version__)

NumPy: 2.3.1


2. Create a 4 x 5 matrix filled with random values. Name it as ```x```.

In [4]:
x = np.random.rand(4, 5)
print(x)

[[0.9490888  0.76696707 0.9361202  0.8620576  0.27650701]
 [0.8040976  0.56349697 0.23220168 0.70937343 0.64006311]
 [0.29232185 0.64614279 0.8607925  0.92884336 0.0775743 ]
 [0.76288528 0.15268902 0.677897   0.50837426 0.78887993]]


3. Create a 3 x 3 matrix filled with [[1, 2, 3], [4, 5, 6], [7, 8, 9]]. Name it as ```y```.

In [5]:
y = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


4. Swap the first two rows of ```x```.

In [6]:
temp = x[0].copy()
x[0] = x[1]
x[1] = temp
print(x)

[[0.8040976  0.56349697 0.23220168 0.70937343 0.64006311]
 [0.9490888  0.76696707 0.9361202  0.8620576  0.27650701]
 [0.29232185 0.64614279 0.8607925  0.92884336 0.0775743 ]
 [0.76288528 0.15268902 0.677897   0.50837426 0.78887993]]


5. Create a random numpy array with shape (100, 2) and name it ```z```. Each row indicates the coordinates of a point. Compute point by point distances.

In [9]:
z = np.random.rand(100, 2)
print("z =", z)

distances = np.zeros((100, 100))
for i in range(100):
    for j in range(100):
        distances[i, j] = np.sqrt(np.sum((z[i] - z[j]) ** 2))

print("distances =", distances)



z = [[8.93577545e-01 1.91585298e-01]
 [8.54619236e-01 8.57041795e-01]
 [5.71845152e-02 5.62980454e-01]
 [3.71587670e-01 5.83389624e-01]
 [4.30070920e-01 5.63122648e-01]
 [9.09963556e-01 9.00704701e-01]
 [3.41628373e-02 3.96805806e-02]
 [3.63830269e-01 5.03471398e-01]
 [3.04212381e-01 7.07596550e-01]
 [8.50595469e-01 2.31879558e-01]
 [1.32355979e-01 7.95740127e-01]
 [9.61340240e-01 7.34125399e-01]
 [4.03186565e-01 8.28262441e-01]
 [3.20746694e-01 6.02529046e-01]
 [6.42084632e-01 7.50846982e-01]
 [1.02225139e-01 5.00585671e-01]
 [2.81054446e-01 9.95537947e-01]
 [4.83408837e-01 3.08380506e-01]
 [9.93530612e-01 9.69035112e-04]
 [9.75053301e-01 4.94882191e-01]
 [2.46066096e-01 2.03920329e-01]
 [2.17685018e-01 6.56553315e-02]
 [3.14228788e-01 6.53927739e-03]
 [6.24465110e-01 2.26138449e-01]
 [9.25593699e-01 4.33613070e-01]
 [6.99674221e-01 6.43171287e-01]
 [7.61445910e-01 9.35117282e-02]
 [6.49870401e-01 8.38565249e-01]
 [4.88478923e-01 1.17822266e-01]
 [7.88360360e-01 7.53938588e-01]
 [3.70

6. Subtract the mean of each row of ```y```.

In [13]:
row_mean = y.mean(axis=1, keepdims=True)
print("Row means:", row_mean)

y = y - row_mean
print("y =", y)

Row means: [[2.]
 [5.]
 [8.]]
y = [[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


7. Add a vector [1, 0, 1] to each row of ```y``` using broadcasting and name the resulting numpy array as ```yy```.

In [14]:
yy = y + np.array([1, 0, 1])
print("yy = ", yy)

yy =  [[0. 0. 2.]
 [0. 0. 2.]
 [0. 0. 2.]]


8. For each row in ```yy```, extract the value that are not equal to the other two values. Organize these values as a numpy array.

In [ ]:
# one question about this quiz.
# the different items are all in the 3rd col in each row;
# So, could I directly extract the 3rd column from the original array?

# resolution 1
result1 = yy[:, 2]
print("Extracted using direct indexing:", result1)

# resolution 2
result2 = []
for row in yy:
    counts = np.sum(row.reshape(-1, 1) == row, axis=1)
    unique_elements = row[counts == 1]
    result2.append(unique_elements[0])
result2 = np.array(result2)
print("Extracted using loop:", result2)

Extracted using direct indexing: [2. 2. 2.]
Extracted using loop: [2. 2. 2.]
